[2025-02-17T18:57:37.912+0000] {processor.py:186} INFO - Started process (PID=3085) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T18:57:37.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T18:57:37.915+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:57:37.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T18:57:37.927+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:57:37.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T18:57:37.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T18:57:37.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.060 seconds
[2025-02-17T18:58:08.600+0000] {processor.py:186} INFO - Started process (PID=3381) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T18:58:08.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T18:58:08.604+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:58:08.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T18:58:08.609+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:58:08.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T18:58:08.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T18:58:08.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T18:58:39.592+0000] {processor.py:186} INFO - Started process (PID=3677) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T18:58:39.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T18:58:39.597+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:58:39.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T18:58:39.602+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:58:39.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T18:58:39.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T18:58:39.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T18:59:10.234+0000] {processor.py:186} INFO - Started process (PID=3979) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T18:59:10.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T18:59:10.240+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:59:10.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T18:59:10.247+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:59:10.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T18:59:10.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T18:59:10.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.044 seconds
[2025-02-17T18:59:40.955+0000] {processor.py:186} INFO - Started process (PID=4275) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T18:59:40.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T18:59:40.959+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:59:40.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T18:59:40.963+0000] {logging_mixin.py:190} INFO - [2025-02-17T18:59:40.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T18:59:40.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T18:59:40.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.044 seconds
[2025-02-17T19:00:11.573+0000] {processor.py:186} INFO - Started process (PID=4571) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:00:11.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:00:11.583+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:00:11.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:00:11.587+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:00:11.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:00:11.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:00:11.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.043 seconds
[2025-02-17T19:00:42.470+0000] {processor.py:186} INFO - Started process (PID=4867) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:00:42.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:00:42.475+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:00:42.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:00:42.499+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:00:42.498+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:00:42.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:00:42.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.052 seconds
[2025-02-17T19:01:13.273+0000] {processor.py:186} INFO - Started process (PID=5163) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:13.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:01:13.278+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:13.277+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:13.283+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:13.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:01:13.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:13.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.054 seconds
[2025-02-17T19:01:44.059+0000] {processor.py:186} INFO - Started process (PID=5459) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:44.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:01:44.063+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:44.063+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:44.068+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:44.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:01:44.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:44.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.028 seconds
[2025-02-17T19:01:54.169+0000] {processor.py:186} INFO - Started process (PID=5687) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:54.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:01:54.170+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:54.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:54.174+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:01:54.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:01:54.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:01:54.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.017 seconds
[2025-02-17T19:02:24.945+0000] {processor.py:186} INFO - Started process (PID=5972) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:02:24.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:02:24.947+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:02:24.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:02:24.951+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:02:24.950+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:02:24.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:02:24.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.019 seconds
[2025-02-17T19:02:55.941+0000] {processor.py:186} INFO - Started process (PID=6263) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:02:55.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:02:55.944+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:02:55.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:02:55.948+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:02:55.947+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:02:55.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:02:55.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.020 seconds
[2025-02-17T19:03:25.994+0000] {processor.py:186} INFO - Started process (PID=6500) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:03:25.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:03:25.998+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:03:25.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:03:26.004+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:03:26.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:03:26.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:03:26.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.043 seconds
[2025-02-17T19:03:56.778+0000] {processor.py:186} INFO - Started process (PID=6796) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:03:56.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:03:56.781+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:03:56.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:03:56.788+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:03:56.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:03:56.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:03:56.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.030 seconds
[2025-02-17T19:04:27.624+0000] {processor.py:186} INFO - Started process (PID=7092) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:04:27.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:04:27.626+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:04:27.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:04:27.634+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:04:27.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-17T19:04:27.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:04:27.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.025 seconds
[2025-02-17T19:04:36.141+0000] {processor.py:186} INFO - Started process (PID=7232) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:04:36.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:04:36.147+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:04:36.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:04:36.155+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:04:36.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 10, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:04:36.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:04:36.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.044 seconds
[2025-02-17T19:05:06.926+0000] {processor.py:186} INFO - Started process (PID=7528) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:06.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:05:06.930+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:06.930+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:06.935+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:06.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 10, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:05:06.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:06.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.030 seconds
[2025-02-17T19:05:07.938+0000] {processor.py:186} INFO - Started process (PID=7533) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:07.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:05:07.941+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:07.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:07.947+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:07.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 31, in <module>
    task1 = SQLExecuteQueryOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'SQLExecuteQueryOperator' is not defined
[2025-02-17T19:05:07.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:07.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.027 seconds
[2025-02-17T19:05:38.588+0000] {processor.py:186} INFO - Started process (PID=7829) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:38.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:05:38.593+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:38.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:38.604+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:38.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 31, in <module>
    task1 = SQLExecuteQueryOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'SQLExecuteQueryOperator' is not defined
[2025-02-17T19:05:38.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:38.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.046 seconds
[2025-02-17T19:05:41.690+0000] {processor.py:186} INFO - Started process (PID=7840) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:41.691+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:05:41.692+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:41.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:41.700+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:05:41.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 32, in <module>
    task1 = SQLExecuteQueryOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 258, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: create_postgres_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_localhost'}
[2025-02-17T19:05:41.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:05:41.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.078 seconds
[2025-02-17T19:06:12.299+0000] {processor.py:186} INFO - Started process (PID=8136) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:06:12.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:06:12.304+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:06:12.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:06:12.313+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:06:12.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 32, in <module>
    task1 = SQLExecuteQueryOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 258, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: create_postgres_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_localhost'}
[2025-02-17T19:06:12.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:06:12.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.034 seconds
[2025-02-17T19:06:42.768+0000] {processor.py:186} INFO - Started process (PID=8432) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:06:42.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:06:42.772+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:06:42.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:06:42.780+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:06:42.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 32, in <module>
    task1 = SQLExecuteQueryOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 258, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: create_postgres_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_localhost'}
[2025-02-17T19:06:42.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:06:42.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T19:07:13.159+0000] {processor.py:186} INFO - Started process (PID=8728) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:07:13.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:07:13.162+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:07:13.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:07:13.170+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:07:13.168+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 32, in <module>
    task1 = SQLExecuteQueryOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 258, in __init__
    super().__init__(conn_id=conn_id, database=database, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 959, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SQLExecuteQueryOperator (task_id: create_postgres_table). Invalid arguments were:
**kwargs: {'postgres_conn_id': 'postgres_localhost'}
[2025-02-17T19:07:13.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:07:13.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.030 seconds
[2025-02-17T19:07:33.186+0000] {processor.py:186} INFO - Started process (PID=8958) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:07:33.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:07:33.190+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:07:33.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:07:33.213+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:07:33.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:07:33.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:07:33.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.057 seconds
[2025-02-17T19:08:03.827+0000] {processor.py:186} INFO - Started process (PID=9253) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:08:03.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:08:03.829+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:08:03.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:08:03.843+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:08:03.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:08:03.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:08:03.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.034 seconds
[2025-02-17T19:08:34.441+0000] {processor.py:186} INFO - Started process (PID=9549) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:08:34.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:08:34.443+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:08:34.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:08:34.468+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:08:34.467+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:08:34.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:08:34.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.044 seconds
[2025-02-17T19:09:05.094+0000] {processor.py:186} INFO - Started process (PID=9845) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:09:05.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:09:05.097+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:09:05.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:09:05.112+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:09:05.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:09:05.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:09:05.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.042 seconds
[2025-02-17T19:09:35.462+0000] {processor.py:186} INFO - Started process (PID=10141) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:09:35.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:09:35.464+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:09:35.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:09:35.476+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:09:35.475+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:09:35.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:09:35.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.035 seconds
[2025-02-17T19:10:06.180+0000] {processor.py:186} INFO - Started process (PID=10436) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:10:06.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:10:06.182+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:10:06.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:10:06.193+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:10:06.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:10:06.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:10:06.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.039 seconds
[2025-02-17T19:10:36.692+0000] {processor.py:186} INFO - Started process (PID=10732) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:10:36.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:10:36.694+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:10:36.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:10:36.704+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:10:36.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:10:36.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:10:36.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.025 seconds
[2025-02-17T19:11:07.243+0000] {processor.py:186} INFO - Started process (PID=11028) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:11:07.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:11:07.246+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:11:07.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:11:07.256+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:11:07.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:11:07.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:11:07.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T19:11:37.858+0000] {processor.py:186} INFO - Started process (PID=11324) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:11:37.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:11:37.861+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:11:37.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:11:37.877+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:11:37.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:11:37.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:11:37.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.037 seconds
[2025-02-17T19:12:08.598+0000] {processor.py:186} INFO - Started process (PID=11620) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:12:08.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:12:08.600+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:12:08.600+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:12:08.610+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:12:08.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:12:08.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:12:08.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.027 seconds
[2025-02-17T19:12:39.315+0000] {processor.py:186} INFO - Started process (PID=11916) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:12:39.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:12:39.317+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:12:39.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:12:39.326+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:12:39.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:12:39.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:12:39.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.035 seconds
[2025-02-17T19:13:10.000+0000] {processor.py:186} INFO - Started process (PID=12212) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:13:10.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:13:10.006+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:13:10.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:13:10.014+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:13:10.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:13:10.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:13:10.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.038 seconds
[2025-02-17T19:13:40.618+0000] {processor.py:186} INFO - Started process (PID=12507) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:13:40.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:13:40.621+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:13:40.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:13:40.633+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:13:40.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:13:40.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:13:40.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.034 seconds
[2025-02-17T19:14:11.258+0000] {processor.py:186} INFO - Started process (PID=12803) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:14:11.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:14:11.261+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:11.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:14:11.278+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:11.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:14:11.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:14:11.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.036 seconds
[2025-02-17T19:14:41.838+0000] {processor.py:186} INFO - Started process (PID=13105) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:14:41.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:14:41.841+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:41.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:14:41.852+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:14:41.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:14:41.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:14:41.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.030 seconds
[2025-02-17T19:15:12.362+0000] {processor.py:186} INFO - Started process (PID=13401) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:15:12.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:15:12.365+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:12.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:15:12.376+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:12.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:15:12.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:15:12.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T19:15:42.828+0000] {processor.py:186} INFO - Started process (PID=13697) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:15:42.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:15:42.830+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:42.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:15:42.846+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:15:42.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:15:42.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:15:42.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.036 seconds
[2025-02-17T19:16:13.449+0000] {processor.py:186} INFO - Started process (PID=13993) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:16:13.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:16:13.454+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:13.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:16:13.469+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:13.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:16:13.469+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:16:13.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.043 seconds
[2025-02-17T19:16:44.030+0000] {processor.py:186} INFO - Started process (PID=14289) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:16:44.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:16:44.033+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:44.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:16:44.045+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:16:44.044+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:16:44.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:16:44.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T19:17:14.803+0000] {processor.py:186} INFO - Started process (PID=14585) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:17:14.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:17:14.806+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:14.805+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:17:14.820+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:14.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:17:14.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:17:14.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T19:17:45.409+0000] {processor.py:186} INFO - Started process (PID=14881) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:17:45.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:17:45.412+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:45.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:17:45.420+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:17:45.419+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:17:45.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:17:45.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T19:18:15.958+0000] {processor.py:186} INFO - Started process (PID=15176) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:18:15.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:18:15.960+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:15.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:18:15.969+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:15.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:18:15.970+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:18:15.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T19:18:46.557+0000] {processor.py:186} INFO - Started process (PID=15472) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:18:46.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:18:46.559+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:46.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:18:46.570+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:18:46.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:18:46.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:18:46.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.029 seconds
[2025-02-17T19:19:17.058+0000] {processor.py:186} INFO - Started process (PID=15768) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:19:17.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:19:17.062+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:17.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:19:17.070+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:17.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:19:17.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:19:17.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.030 seconds
[2025-02-17T19:19:47.726+0000] {processor.py:186} INFO - Started process (PID=16064) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:19:47.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:19:47.729+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:47.729+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:19:47.738+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:19:47.737+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:19:47.738+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:19:47.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.032 seconds
[2025-02-17T19:20:18.341+0000] {processor.py:186} INFO - Started process (PID=16360) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:20:18.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:20:18.344+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:18.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:20:18.355+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:18.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:20:18.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:20:18.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.035 seconds
[2025-02-17T19:20:48.935+0000] {processor.py:186} INFO - Started process (PID=16656) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:20:48.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:20:48.937+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:48.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:20:48.950+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:20:48.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:20:48.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:20:48.962+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.032 seconds
[2025-02-17T19:21:19.648+0000] {processor.py:186} INFO - Started process (PID=16952) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:21:19.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:21:19.651+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:19.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:21:19.657+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:19.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:21:19.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:21:19.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.026 seconds
[2025-02-17T19:21:50.168+0000] {processor.py:186} INFO - Started process (PID=17248) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:21:50.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:21:50.172+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:50.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:21:50.177+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:21:50.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:21:50.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:21:50.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.028 seconds
[2025-02-17T19:22:20.533+0000] {processor.py:186} INFO - Started process (PID=17544) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:22:20.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:22:20.535+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:20.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:22:20.547+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:20.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:22:20.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:22:20.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.035 seconds
[2025-02-17T19:22:50.972+0000] {processor.py:186} INFO - Started process (PID=17840) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:22:50.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:22:50.974+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:50.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:22:50.989+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:22:50.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:22:50.990+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:22:51.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T19:23:21.775+0000] {processor.py:186} INFO - Started process (PID=18136) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:23:21.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:23:21.777+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:21.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:23:21.785+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:21.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:23:21.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:23:21.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.027 seconds
[2025-02-17T19:23:52.024+0000] {processor.py:186} INFO - Started process (PID=18432) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:23:52.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:23:52.026+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:52.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:23:52.031+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:23:52.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:23:52.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:23:52.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.027 seconds
[2025-02-17T19:24:22.089+0000] {processor.py:186} INFO - Started process (PID=18728) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:24:22.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:24:22.090+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:24:22.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:24:22.092+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:24:22.092+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:24:22.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:24:22.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.013 seconds
[2025-02-17T19:25:18.558+0000] {processor.py:186} INFO - Started process (PID=18793) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:25:18.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:25:18.561+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:25:18.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:25:18.570+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:25:18.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:25:18.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:25:18.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T19:25:49.356+0000] {processor.py:186} INFO - Started process (PID=19089) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:25:49.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:25:49.360+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:25:49.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:25:49.372+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:25:49.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:25:49.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:25:49.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.040 seconds
[2025-02-17T19:42:10.048+0000] {processor.py:186} INFO - Started process (PID=19385) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:42:10.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:42:10.050+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:42:10.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:42:10.058+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:42:10.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:42:10.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:42:10.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T19:43:04.306+0000] {processor.py:186} INFO - Started process (PID=19681) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:43:04.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:43:04.308+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:43:04.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:43:04.318+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:43:04.317+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:43:04.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:43:04.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.037 seconds
[2025-02-17T19:43:35.182+0000] {processor.py:186} INFO - Started process (PID=19977) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T19:43:35.183+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T19:43:35.187+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:43:35.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T19:43:35.196+0000] {logging_mixin.py:190} INFO - [2025-02-17T19:43:35.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T19:43:35.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T19:43:35.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.043 seconds
[2025-02-17T20:00:43.275+0000] {processor.py:186} INFO - Started process (PID=20273) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:00:43.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:00:43.278+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:00:43.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:00:43.290+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:00:43.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:00:43.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:00:43.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.037 seconds
[2025-02-17T20:01:13.959+0000] {processor.py:186} INFO - Started process (PID=20569) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:01:13.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:01:13.962+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:01:13.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:01:13.970+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:01:13.969+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:01:13.970+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:01:13.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.030 seconds
[2025-02-17T20:17:02.474+0000] {processor.py:186} INFO - Started process (PID=20865) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:17:02.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:17:02.478+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:17:02.477+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:17:02.483+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:17:02.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:17:02.484+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:17:02.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T20:17:32.878+0000] {processor.py:186} INFO - Started process (PID=21161) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:17:32.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:17:32.881+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:17:32.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:17:32.890+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:17:32.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:17:32.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:17:32.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.032 seconds
[2025-02-17T20:33:16.357+0000] {processor.py:186} INFO - Started process (PID=21457) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:33:16.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:33:16.360+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:33:16.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:33:16.366+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:33:16.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:33:16.366+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:33:16.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.032 seconds
[2025-02-17T20:33:47.224+0000] {processor.py:186} INFO - Started process (PID=21753) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:33:47.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:33:47.228+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:33:47.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:33:47.235+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:33:47.234+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:33:47.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:33:47.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.037 seconds
[2025-02-17T20:44:14.665+0000] {processor.py:186} INFO - Started process (PID=22049) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:44:14.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:44:14.672+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:44:14.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:44:14.683+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:44:14.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:44:14.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:44:14.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.055 seconds
[2025-02-17T20:44:45.017+0000] {processor.py:186} INFO - Started process (PID=22345) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:44:45.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:44:45.021+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:44:45.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:44:45.032+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:44:45.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:44:45.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:44:45.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.042 seconds
[2025-02-17T20:45:15.715+0000] {processor.py:186} INFO - Started process (PID=22641) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:45:15.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:45:15.718+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:45:15.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:45:15.725+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:45:15.724+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:45:15.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:45:15.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T20:45:46.103+0000] {processor.py:186} INFO - Started process (PID=22937) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:45:46.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:45:46.106+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:45:46.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:45:46.116+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:45:46.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:45:46.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:45:46.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.036 seconds
[2025-02-17T20:50:26.476+0000] {processor.py:186} INFO - Started process (PID=23233) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T20:50:26.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T20:50:26.487+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:50:26.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T20:50:26.508+0000] {logging_mixin.py:190} INFO - [2025-02-17T20:50:26.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T20:50:26.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T20:50:26.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.058 seconds
[2025-02-17T21:07:04.224+0000] {processor.py:186} INFO - Started process (PID=23529) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T21:07:04.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T21:07:04.226+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:07:04.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T21:07:04.229+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:07:04.229+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T21:07:04.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T21:07:04.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.022 seconds
[2025-02-17T21:07:34.696+0000] {processor.py:186} INFO - Started process (PID=23825) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T21:07:34.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T21:07:34.698+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:07:34.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T21:07:34.706+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:07:34.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T21:07:34.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T21:07:34.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.026 seconds
[2025-02-17T21:08:05.362+0000] {processor.py:186} INFO - Started process (PID=24121) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T21:08:05.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T21:08:05.365+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:08:05.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T21:08:05.378+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:08:05.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T21:08:05.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T21:08:05.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T21:08:35.961+0000] {processor.py:186} INFO - Started process (PID=24417) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T21:08:35.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T21:08:35.965+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:08:35.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T21:08:35.983+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:08:35.975+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T21:08:35.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T21:08:36.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.054 seconds
[2025-02-17T21:25:10.211+0000] {processor.py:186} INFO - Started process (PID=24713) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T21:25:10.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T21:25:10.213+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:25:10.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T21:25:10.222+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:25:10.216+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T21:25:10.224+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T21:25:10.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T21:25:40.655+0000] {processor.py:186} INFO - Started process (PID=25009) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T21:25:40.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T21:25:40.658+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:25:40.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T21:25:40.672+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:25:40.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T21:25:40.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T21:25:40.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.037 seconds
[2025-02-17T21:43:11.417+0000] {processor.py:186} INFO - Started process (PID=25305) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T21:43:11.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T21:43:11.419+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:43:11.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T21:43:11.427+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:43:11.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T21:43:11.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T21:43:11.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.027 seconds
[2025-02-17T21:59:32.228+0000] {processor.py:186} INFO - Started process (PID=25601) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T21:59:32.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T21:59:32.239+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:59:32.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T21:59:32.254+0000] {logging_mixin.py:190} INFO - [2025-02-17T21:59:32.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T21:59:32.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T21:59:32.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.102 seconds
[2025-02-17T22:00:02.821+0000] {processor.py:186} INFO - Started process (PID=25897) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:00:02.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:00:02.824+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:00:02.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:00:02.832+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:00:02.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:00:02.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:00:02.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.043 seconds
[2025-02-17T22:17:03.282+0000] {processor.py:186} INFO - Started process (PID=26193) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:17:03.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:17:03.285+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:17:03.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:17:03.294+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:17:03.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:17:03.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:17:03.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.034 seconds
[2025-02-17T22:17:33.713+0000] {processor.py:186} INFO - Started process (PID=26489) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:17:33.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:17:33.716+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:17:33.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:17:33.728+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:17:33.727+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:17:33.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:17:33.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T22:18:04.181+0000] {processor.py:186} INFO - Started process (PID=26785) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:18:04.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:18:04.188+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:18:04.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:18:04.198+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:18:04.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:18:04.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:18:04.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.064 seconds
[2025-02-17T22:18:34.750+0000] {processor.py:186} INFO - Started process (PID=27081) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:18:34.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:18:34.752+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:18:34.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:18:34.762+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:18:34.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:18:34.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:18:34.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.028 seconds
[2025-02-17T22:19:05.148+0000] {processor.py:186} INFO - Started process (PID=27377) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:19:05.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:19:05.153+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:19:05.153+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:19:05.161+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:19:05.160+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:19:05.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:19:05.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.040 seconds
[2025-02-17T22:19:35.620+0000] {processor.py:186} INFO - Started process (PID=27673) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:19:35.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:19:35.622+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:19:35.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:19:35.630+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:19:35.626+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:19:35.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:19:35.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T22:20:06.317+0000] {processor.py:186} INFO - Started process (PID=27969) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:20:06.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:20:06.321+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:20:06.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:20:06.334+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:20:06.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:20:06.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:20:06.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.041 seconds
[2025-02-17T22:20:36.937+0000] {processor.py:186} INFO - Started process (PID=28265) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:20:36.938+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:20:36.940+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:20:36.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:20:36.945+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:20:36.944+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:20:36.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:20:36.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.030 seconds
[2025-02-17T22:21:07.411+0000] {processor.py:186} INFO - Started process (PID=28561) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:21:07.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:21:07.412+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:21:07.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:21:07.419+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:21:07.418+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:21:07.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:21:07.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.019 seconds
[2025-02-17T22:21:37.877+0000] {processor.py:186} INFO - Started process (PID=28857) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:21:37.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:21:37.881+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:21:37.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:21:37.888+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:21:37.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:21:37.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:21:37.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.036 seconds
[2025-02-17T22:22:08.668+0000] {processor.py:186} INFO - Started process (PID=29153) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:22:08.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:22:08.671+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:22:08.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:22:08.684+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:22:08.680+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:22:08.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:22:08.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.043 seconds
[2025-02-17T22:22:39.427+0000] {processor.py:186} INFO - Started process (PID=29449) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:22:39.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:22:39.431+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:22:39.430+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:22:39.445+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:22:39.443+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:22:39.445+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:22:39.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.041 seconds
[2025-02-17T22:23:10.202+0000] {processor.py:186} INFO - Started process (PID=29745) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:23:10.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:23:10.205+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:23:10.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:23:10.214+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:23:10.213+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:23:10.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:23:10.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.031 seconds
[2025-02-17T22:23:41.072+0000] {processor.py:186} INFO - Started process (PID=30041) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:23:41.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:23:41.076+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:23:41.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:23:41.085+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:23:41.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:23:41.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:23:41.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.037 seconds
[2025-02-17T22:24:11.853+0000] {processor.py:186} INFO - Started process (PID=30337) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:24:11.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:24:11.856+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:24:11.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:24:11.869+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:24:11.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:24:11.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:24:11.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.039 seconds
[2025-02-17T22:24:42.573+0000] {processor.py:186} INFO - Started process (PID=30633) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:24:42.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:24:42.577+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:24:42.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:24:42.592+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:24:42.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:24:42.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:24:42.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.042 seconds
[2025-02-17T22:25:13.290+0000] {processor.py:186} INFO - Started process (PID=30929) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:25:13.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:25:13.293+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:25:13.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:25:13.299+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:25:13.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:25:13.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:25:13.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.028 seconds
[2025-02-17T22:25:44.069+0000] {processor.py:186} INFO - Started process (PID=31225) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:25:44.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:25:44.072+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:25:44.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:25:44.085+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:25:44.084+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:25:44.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:25:44.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.035 seconds
[2025-02-17T22:26:14.605+0000] {processor.py:186} INFO - Started process (PID=31521) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:26:14.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:26:14.609+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:26:14.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:26:14.623+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:26:14.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:26:14.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:26:14.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.038 seconds
[2025-02-17T22:26:45.450+0000] {processor.py:186} INFO - Started process (PID=31817) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:26:45.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:26:45.454+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:26:45.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:26:45.466+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:26:45.462+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:26:45.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:26:45.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.039 seconds
[2025-02-17T22:27:16.172+0000] {processor.py:186} INFO - Started process (PID=32113) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:27:16.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:27:16.175+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:27:16.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:27:16.187+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:27:16.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:27:16.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:27:16.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.038 seconds
[2025-02-17T22:27:46.964+0000] {processor.py:186} INFO - Started process (PID=32415) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:27:46.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:27:46.968+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:27:46.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:27:46.977+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:27:46.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:27:46.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:27:46.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.034 seconds
[2025-02-17T22:28:17.594+0000] {processor.py:186} INFO - Started process (PID=32711) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:28:17.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:28:17.597+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:28:17.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:28:17.610+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:28:17.603+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:28:17.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:28:17.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.037 seconds
[2025-02-17T22:28:48.255+0000] {processor.py:186} INFO - Started process (PID=33007) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:28:48.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:28:48.259+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:28:48.259+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:28:48.272+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:28:48.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:28:48.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:28:48.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.038 seconds
[2025-02-17T22:29:18.808+0000] {processor.py:186} INFO - Started process (PID=33303) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:29:18.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:29:18.811+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:29:18.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:29:18.820+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:29:18.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:29:18.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:29:18.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.030 seconds
[2025-02-17T22:29:49.363+0000] {processor.py:186} INFO - Started process (PID=33599) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:29:49.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:29:49.366+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:29:49.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:29:49.374+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:29:49.373+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:29:49.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:29:49.389+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.033 seconds
[2025-02-17T22:30:19.799+0000] {processor.py:186} INFO - Started process (PID=33895) to work on /opt/airflow/dags/DAG1.py
[2025-02-17T22:30:19.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DAG1.py for tasks to queue
[2025-02-17T22:30:19.806+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:30:19.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DAG1.py
[2025-02-17T22:30:19.846+0000] {logging_mixin.py:190} INFO - [2025-02-17T22:30:19.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DAG1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG1.py", line 12, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-02-17T22:30:19.848+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG1.py
[2025-02-17T22:30:19.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DAG1.py took 0.240 seconds
